name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  resolve:
    uses: ./.github/workflows/resolve.yml
  build:
    needs: resolve
    uses: ./.github/workflows/build.yml
    with:
      catala_ref: ${{ needs.resolve.outputs.catala }}
      catala_format_ref: ${{ needs.resolve.outputs.catala_format }}
      catala_lsp_ref: ${{ needs.resolve.outputs.catala_lsp }}
      kind: testing
